import Head from "next/head";
import { Tajawal } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LandingPage from "@/components/LandingPage";

const tajawal = Tajawal({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export default function Home() {
  return (
    <>
      <Head>
        <title>Zamakan</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${tajawal.className}`} dir="rtl">
        <LandingPage />
      </main>
    </>
  );
}
